# Generated by Django 3.2.3 on 2021-07-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
