# Generated by Django 3.2.3 on 2021-07-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_auto_20210711_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('event_id', models.IntegerField()),
            ],
        ),
    ]
