# Generated by Django 3.2.3 on 2021-07-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='soft_delete',
            field=models.BooleanField(null=True),
        ),
    ]
