# Generated by Django 3.2.3 on 2021-07-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_events_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restore_Approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
            ],
        ),
    ]
